=== artefactual-sdps/nraa-enduro-workflows/hack/sips/SIP_20160101_MOSA_2016_001/header/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://nraa.gov.om/sip/v1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="digitalObjectType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="originalName"/>
            <xs:element type="xs:string" name="checksumAlgorithm"/>
            <xs:element type="xs:string" name="checksum"/>
        </xs:sequence>
        <xs:attribute name="id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="7"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="folderType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="originalName"/>
            <xs:element type="v1:digitalObjectType" name="digitalObject" maxOccurs="unbounded" minOccurs="0"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="v1:folderType" name="folder" maxOccurs="unbounded" minOccurs="0"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tocType">
        <xs:sequence>
            <xs:element type="v1:folderType" name="folder" maxOccurs="unbounded" minOccurs="1"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="creationTimePeriodType">
        <xs:sequence>
            <xs:element type="xs:date" name="from"/>
            <xs:element type="xs:date" name="until"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="provenanceType">
        <xs:sequence>
            <xs:element type="xs:string" name="creatorName"/>
            <xs:element type="xs:string" name="systemName"/>
            <xs:element type="xs:string" name="systemDescription"/>
            <xs:element type="xs:string" name="systemRelated"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="retentionSeriesType">
        <xs:sequence>
            <xs:element type="xs:string" name="retentionSeriesNumber"/>
            <xs:element type="xs:string" name="retentionSeriesTitle"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="attributeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="additionalInfoType">
        <xs:sequence>
            <xs:element type="v1:attributeType" name="attribute" maxOccurs="unbounded" minOccurs="0"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="relationshipType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="ref" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="7"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="relationshipsType">
        <xs:sequence>
            <xs:element type="v1:relationshipType" name="relationship" maxOccurs="unbounded" minOccurs="1"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="securityLevelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="U"/> <!-- UNCLASSIFIED -->
            <xs:enumeration value="C"/> <!-- CONFIDENTIAL -->
            <xs:enumeration value="R"/> <!-- RESTRICTED -->
            <xs:enumeration value="S"/> <!-- SECRET -->
            <xs:enumeration value="T"/> <!-- TOP SECRET -->
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="formOfAppearanceType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="unspecified"/>
            <xs:enumeration value="digital"/>
            <xs:enumeration value="non-digital"/>
            <xs:enumeration value="mixed"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="recordType">
        <xs:sequence>
            <xs:element name="title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="recordNumber">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="recordType"/>
            <xs:element type="xs:date" name="dateRegistered"/>
            <xs:element type="xs:string" name="author"/>
            <xs:element type="xs:string" name="creator"/>
            <xs:element type="v1:securityLevelType" name="securityLevel" xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="v1:formOfAppearanceType" name="formOfAppearance" xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element name="digitalObjectRef" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="7"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="v1:additionalInfoType" name="additionalInfo" minOccurs="0"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="v1:relationshipsType" name="relationships" minOccurs="0"
                        xmlns:v1="http://nraa.gov.om/sip/v1">
                <xs:unique name="uniqueRelationshipItemsWithinRecord">
                    <xs:selector xpath=".//v1:relationship"/>
                    <xs:field xpath="@type"/>
                    <xs:field xpath="@ref"/>
                    <!-- The combination of type and ref must be unique for relationships in any
                    given record (but not necessarily across multiple records) -->
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="7"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="fileVolumeType">
        <xs:sequence>
            <xs:element type="v1:creationTimePeriodType" name="creationTimePeriod"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="xs:date" name="dateClosed"/>
            <xs:element type="xs:string" name="creator"/>
            <xs:element type="v1:recordType" name="record" maxOccurs="unbounded" minOccurs="1"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
        <xs:attribute name="id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="7"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="fileNumber" use="required"/>
        <xs:attribute type="xs:integer" name="volumeNumber" use="required"/>
    </xs:complexType>
    <xs:complexType name="fileType">
        <xs:sequence>
            <xs:element name="title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="v1:creationTimePeriodType" name="creationTimePeriod"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="v1:securityLevelType" name="securityLevel" xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="xs:string" name="organisationUnitResponsible"/>
            <xs:element type="xs:string" name="description"/>
            <xs:element type="v1:retentionSeriesType" name="retentionSeries" xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="v1:formOfAppearanceType" name="formOfAppearance" xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="v1:fileVolumeType" name="fileVolume" maxOccurs="unbounded" minOccurs="1"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
        <xs:attribute name="id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="7"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="fileNumber" use="required"/>
    </xs:complexType>
    <xs:complexType name="classificationLevelType">
        <xs:sequence>
            <xs:element name="title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="v1:fileType" name="file" minOccurs="0" xmlns:v1="http://nraa.gov.om/sip/v1">
                <xs:unique name="uniqueFileVolumeNumberWithinFile">
                    <xs:selector xpath="./v1:fileVolume"/>
                    <xs:field xpath="@volumeNumber"/>
                    <!-- The volume number need only be unique among file volumes within the same file.
                    It need not be unique among file volumes from different files -->
                </xs:unique>
            </xs:element>
            <xs:element type="v1:classificationLevelType" name="classificationLevel" minOccurs="0"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
        <xs:attribute name="id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="7"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="levelNumber" use="required"/>
    </xs:complexType>
    <xs:complexType name="classificationSystemType">
        <xs:sequence>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="classificationSystemVersion"/>
            <xs:element type="v1:classificationLevelType" name="classificationLevel"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="submissionType">
        <xs:sequence>
            <xs:element name="submissionType">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="EDRMS"/>
                        <!-- At the moment, only EDRMS is allowed
                        <xs:enumeration value="FILES"/>
                        -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="submittingOrganisation">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="submissionNumber">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="transferApprovalReference">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="v1:creationTimePeriodType" name="creationTimePeriod"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="xs:string" name="protectionPeriodCategory"/>
            <xs:element type="xs:string" name="protectionPeriod"/>
            <xs:element type="xs:string" name="protectionPeriodArguments"/>
            <xs:element type="v1:provenanceType" name="provenance" xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="v1:classificationSystemType" name="classificationSystem"
                        xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="packageType">
        <xs:sequence>
            <xs:element name="packageType" >
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="SIP"/>
                        <!-- At the moment, only SIP is allowed
                        <xs:enumeration value="AIP"/>
                        <xs:enumeration value="DIP"/>
                        -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="v1:tocType" name="toc" xmlns:v1="http://nraa.gov.om/sip/v1"/>
            <xs:element type="v1:submissionType" name="submission" xmlns:v1="http://nraa.gov.om/sip/v1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="schemaVersion"/>
    </xs:complexType>
    <xs:element name="package" type="v1:packageType" xmlns:v1="http://nraa.gov.om/sip/v1">
        <xs:unique name="uniqueDigitalObjectId">
            <xs:selector xpath=".//v1:digitalObject"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="uniqueClassificationLevelId">
            <xs:selector xpath=".//v1:classificationLevel"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="uniqueClassificationLevelLevelNumber">
            <xs:selector xpath=".//v1:classificationLevel"/>
            <xs:field xpath="@levelNumber"/>
        </xs:unique>
        <xs:unique name="uniquefileOrFileVolumeId">
            <xs:selector xpath=".//v1:file|.//v1:fileVolume"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="uniquefileOrFileVolumeNumber">
            <xs:selector xpath=".//v1:file|.//v1:fileVolume"/>
            <xs:field xpath="@fileNumber"/>
        </xs:unique>
        <xs:unique name="uniqueRecordId">
            <xs:selector xpath=".//v1:record"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="uniqueDigitalObjectRef">
            <xs:selector xpath=".//v1:digitalObjectRef"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== artefactual-sdps/nraa-enduro-workflows/hack/sips/SIP_20160101_MOSA_2016_001/header/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://nraa.gov.om/sip/v1"
		 schemaVersion="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd">
	<packageType>SIP</packageType>
	<toc>
		<folder>
			<name>header</name>
			<originalName>header</originalName>
			<digitalObject id="d000017">
				<name>metadata.xsd</name>
				<originalName>metadata.xsd</originalName>
				<checksumAlgorithm>MD5</checksumAlgorithm>
				<checksum>43b5f8556677eaaab9960e22c043adab</checksum>
			</digitalObject>
		</folder>
		<folder>
			<name>content</name>
			<originalName>content</originalName>
			<folder>
				<name>f000001</name>
				<originalName>f000001</originalName>
				<folder>
					<name>f000002</name>
					<originalName>f000002</originalName>
					<digitalObject id="d000001">
						<name>d000001.xml</name>
						<originalName>acceptance-invite.xml
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000002">
						<name>d000002.xml</name>
						<originalName>working-paper-1.xml
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000003">
						<name>d000003.xml</name>
						<originalName>working-paper-2.xml
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000004">
						<name>d000004.dotx</name>
						<originalName>working-paper-3.dotx
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000005">
						<name>d000005.pdf</name>
						<originalName>reference-pub-1.pdf
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000006">
						<name>d000006.xml</name>
						<originalName>reference-pub-2.xml</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000007">
						<name>d000007.pdf</name>
						<originalName>reference-pub-3.pdf</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
				</folder>
				<folder>
					<name>f000003</name>
					<originalName>f000003</originalName>
					<digitalObject id="d000008">
						<name>d000008.pdf</name>
						<originalName>minutes-1.pdf</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000009">
						<name>d000009.jpg</name>
						<originalName>minutes-2.jpg</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000010">
						<name>d000010.xml</name>
						<originalName>minutes-3.xml</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000011">
						<name>d000011.pdf</name>
						<originalName>tech-1.pdf</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000012">
						<name>d000012.pdf</name>
						<originalName>tech-2.pdf
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000013">
						<name>d000013.xml</name>
						<originalName>tech-3.xml
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000014">
						<name>d000014.pdf</name>
						<originalName>attend-1.pdf
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000015">
						<name>d000015.pdf</name>
						<originalName>attend-2.pdf
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
					<digitalObject id="d000016">
						<name>d000016.pdf</name>
						<originalName>attend-3.pdf
						</originalName>
						<checksumAlgorithm>MD5</checksumAlgorithm>
						<checksum>d41d8cd98f00b204e9800998ecf8427e</checksum>
					</digitalObject>
				</folder>
			</folder>
		</folder>
	</toc>
	<submission>
		<submissionType>EDRMS</submissionType>
		<submittingOrganisation>MOSA</submittingOrganisation>
		<submissionNumber>MOSA-2016-1</submissionNumber>
		<transferApprovalReference>NRAA-9999/2016.1</transferApprovalReference>
		<creationTimePeriod>
			<from>2016-01-01</from>
			<until>2016-12-31</until>
		</creationTimePeriod>
		<protectionPeriodCategory>Article 27 of Records and Archives Law</protectionPeriodCategory>
		<protectionPeriod>60</protectionPeriod>
		<protectionPeriodArguments>Records related to investigations and statistics</protectionPeriodArguments>
		<provenance>
			<creatorName>MOSA</creatorName>
			<systemName>CMS, V5.4.1</systemName>
			<systemDescription>System acquired in 1990. Technology based on Microsoft .NET Platform </systemDescription>
			<systemRelated>None</systemRelated>
		</provenance>
		<classificationSystem>
			<name>MOSA-BCS-2011</name>
			<classificationSystemVersion>1.0</classificationSystemVersion>
			<classificationLevel id="c000001"
				levelNumber="1000">
				<title>General Administration</title>
				<classificationLevel id="c000002"
					levelNumber="1200">
					<title>Office of the Head of Agency</title>
					<classificationLevel id="c000003"
						levelNumber="1230">
						<title>Committees and Councils</title>
						<classificationLevel id="c000004"
							levelNumber="1234">
							<title>Consultative Council Meeting</title>
							<file id="f000001" fileNumber="1234/2016-16">
								<title>Trade Pricing Council Meeting</title>
								<creationTimePeriod>
									<from>2016-01-01</from>
									<until>2016-12-31</until>
								</creationTimePeriod>
								<securityLevel>U</securityLevel>
								<organisationUnitResponsible>Office of the Chairman</organisationUnitResponsible>
								<description>File for all the records related to the 1st Trade Pricing Council Meeting</description>
								<retentionSeries>
									<retentionSeriesNumber>4,3,2,1</retentionSeriesNumber>
									<retentionSeriesTitle>Consultative Council Meeting Series</retentionSeriesTitle>
								</retentionSeries>
								<formOfAppearance>digital</formOfAppearance>
								<fileVolume id="f000002" fileNumber="1234/2016-16V1" volumeNumber="1">
									<creationTimePeriod>
										<from>2016-01-01</from>
										<until>2016-06-30</until>
									</creationTimePeriod>
									<dateClosed>2016-06-30</dateClosed>
									<creator>Yahya Abdullah</creator>
									<record id="r000001">
										<title>Acceptance of Invitation to 1st Trade Pricing Council Meeting</title>
										<recordNumber>1234/2016-16V1.1</recordNumber>
										<recordType>Correspondence</recordType>
										<dateRegistered>2016-01-01</dateRegistered>
										<author>Yahya Abdullah</author>
										<creator>Marya Al-Siyabi</creator>
										<securityLevel>U</securityLevel>
										<formOfAppearance>digital</formOfAppearance>
										<digitalObjectRef>d000001</digitalObjectRef>
										<additionalInfo>
											<attribute name="sender_organization">Ministry of Finance</attribute>
											<attribute name="date_sent">2016-01-01</attribute>
										</additionalInfo>
										<relationships>
											<relationship type="RELATES TO" ref="r000005"/>
											<relationship type="RELATES TO" ref="r000006"/>
										</relationships>
									</record>
									<record id="r000002">
										<title>Working Papers for 1st Meeting</title>
										<recordNumber>1234/2016-16V1.2</recordNumber>
										<recordType>Working Paper</recordType>
										<dateRegistered>2016-03-01</dateRegistered>
										<author>Yahya Abdullah</author>
										<creator>Marya Al-Siyabi</creator>
										<securityLevel>U</securityLevel>
										<formOfAppearance>digital</formOfAppearance>
										<digitalObjectRef>d000002</digitalObjectRef>
										<digitalObjectRef>d000003</digitalObjectRef>
										<digitalObjectRef>d000004</digitalObjectRef>
									</record>
									<record id="r000003">
										<title>Reference Publications for 1st Meeting</title>
										<recordNumber>1234/2016-16V1.3</recordNumber>
										<recordType>Publication</recordType>
										<dateRegistered>2016-06-30</dateRegistered>
										<author>Yahya Abdullah</author>
										<creator>Marya Al-Siyabi</creator>
										<securityLevel>U</securityLevel>
										<formOfAppearance>digital</formOfAppearance>
										<digitalObjectRef>d000005</digitalObjectRef>
										<digitalObjectRef>d000006</digitalObjectRef>
										<digitalObjectRef>d000007</digitalObjectRef>
									</record>
								</fileVolume>
								<fileVolume id="f000003" fileNumber="1234/2016-16V2" volumeNumber="2">
									<creationTimePeriod>
										<from>2016-06-30</from>
										<until>2016-12-31</until>
									</creationTimePeriod>
									<dateClosed>2016-12-31</dateClosed>
									<creator>Yahya Abdullah</creator>
									<record id="r000004">
										<title>Minutes of Meeting for 1st Trade Pricing Council Meeting</title>
